# Generated by Django 5.1 on 2024-09-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('trek', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trek_date', models.DateField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('accommodation', models.TextField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('equipment_rental', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('liability_waiver', models.BooleanField(default=False)),
            ],
        ),
    ]
