# Generated by Django 5.1 on 2024-09-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
