# Generated by Django 5.1 on 2024-09-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_review_experiencelevel_review_groupsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='experienceLevel',
        ),
        migrations.RemoveField(
            model_name='review',
            name='groupSize',
        ),
        migrations.RemoveField(
            model_name='review',
            name='trekDifficulty',
        ),
        migrations.RemoveField(
            model_name='review',
            name='trekDuration',
        ),
        migrations.RemoveField(
            model_name='review',
            name='trekType',
        ),
        migrations.RemoveField(
            model_name='review',
            name='trekWeather',
        ),
        migrations.RemoveField(
            model_name='review',
            name='wouldRecommend',
        ),
    ]
